apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: geoduels

resources:
  - ../../base
  - namespace.yaml
  - runtime-config.yaml
  - ingress.yaml

images:
  - name: ghcr.io/sourcelocation/geoduels-api
    newTag: latest
  - name: ghcr.io/sourcelocation/geoduels-match-coordinator
    newTag: latest
  - name: ghcr.io/sourcelocation/geoduels-moderation-worker
    newTag: latest
  - name: ghcr.io/sourcelocation/geoduels-realtime-gateway
    newTag: latest
  - name: ghcr.io/sourcelocation/geoduels-gameplay-node
    newTag: latest
  - name: ghcr.io/sourcelocation/geoduels-web
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: geoduels

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-creds
    target:
      kind: Deployment
  - patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-creds
    target:
      kind: StatefulSet
      name: gameplay-node
  - target:
      kind: Deployment
      name: api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: match-coordinator
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: moderation-worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: realtime-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: StatefulSet
      name: gameplay-node
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
